// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NiuDialog: typeof import('./src/componentsAuto/niu-dialog/niu-dialog.vue')['default']
    NiuMask: typeof import('./src/componentsAuto/niu-mask/niu-mask.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/componentsAuto/SvgIcon/SvgIcon.vue')['default']
  }
}

export {}
