/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Devtool: typeof import('./src/componentsAuto/Devtool/Devtool.vue')['default']
    LRLayout: typeof import('./src/componentsAuto/Layout/LRLayout.vue')['default']
    NiuAdjustWidth: typeof import('./src/componentsAuto/niu-adjust-width/niu-adjust-width.vue')['default']
    NiuImage: typeof import('./src/componentsAuto/niu-image/niu-image.vue')['default']
    Preview: typeof import('./src/componentsAuto/Preview/Preview.vue')['default']
    PsTree: typeof import('princess-ui')['PsTree']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/componentsAuto/SvgIcon/SvgIcon.vue')['default']
  }
}
